# Generated by Django 4.0.1 on 2022-05-09 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('methodist', '0006_student_educational_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('semester', models.PositiveIntegerField(verbose_name='Семестер')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='methodist.student')),
            ],
            options={
                'verbose_name': 'Файл користувача',
                'verbose_name_plural': 'Файли користувача',
            },
        ),
    ]
