# Generated by Django 4.0.1 on 2022-05-11 20:29

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_student_educational_program'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsource',
            name='file',
            field=models.FileField(upload_to=student.models.gen_path),
        ),
        migrations.AlterField(
            model_name='studentsource',
            name='semester',
            field=models.PositiveIntegerField(null=True, verbose_name='Семестер'),
        ),
        migrations.AlterField(
            model_name='studentsource',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_source', to='methodist.student'),
        ),
    ]
