# Generated by Django 4.0.1 on 2022-05-14 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_student_educational_program'),
        ('student', '0002_alter_studentsource_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsource',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_source', to='methodist.student'),
        ),
    ]
