# Generated by Django 4.0.1 on 2022-05-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_student_educational_program'),
        ('student', '0004_alter_studentsource_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsource',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_source', to='methodist.student'),
            preserve_default=False,
        ),
    ]
