# Generated by Django 4.0.1 on 2022-06-17 18:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentsource_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsource',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='studentsource',
            name='type_file',
            field=models.CharField(default='Audio', max_length=32, verbose_name='Тип файла'),
        ),
    ]
