# Generated by Django 4.0.1 on 2022-06-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
