# Generated by Django 4.0.1 on 2022-04-17 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('methodist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='rating_unique',
        ),
        migrations.RemoveField(
            model_name='extrapoints',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='group',
            name='department',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
        migrations.AddField(
            model_name='group',
            name='educational_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='methodist.educationalprogram', verbose_name='Освітня програма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rating',
            name='is_annual_assessment',
            field=models.BooleanField(default=False, verbose_name='Річна оцінка'),
        ),
        migrations.AddField(
            model_name='subject',
            name='educational_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='methodist.educationalprogram', verbose_name='Освітня програма'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='extrapoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_points_students', to='methodist.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='methodist.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='student',
            name='educational_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodist.educationalprogram', verbose_name='Освітня програма'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', related_query_name='student_group', to='methodist.group', verbose_name='Група'),
        ),
        migrations.AlterField(
            model_name='student',
            name='update_at',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Рік коли був відредагований студент'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='form_of_control',
            field=models.CharField(choices=[('Екзамен', 'Екзамен'), ('Залік', 'Залік'), ('Курсова', 'Курсова'), ('Практика', 'Практика')], max_length=20, verbose_name='Форма конролю'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(related_name='user_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Викладачі'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'subject', 'semester', 'is_annual_assessment'), name='rating_unique'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('name_subject', 'group'), name='name_subject_unique'),
        ),
    ]
