# Generated by Django 4.0.1 on 2022-04-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0002_remove_rating_rating_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['id'], 'verbose_name': 'Предмет', 'verbose_name_plural': 'Предмети'},
        ),
    ]
