# Generated by Django 4.0.1 on 2022-04-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0004_alter_subject_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='educational_program',
        ),
    ]
