# Generated by Django 4.0.1 on 2022-04-27 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0005_remove_student_educational_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='educational_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='methodist.educationalprogram', verbose_name='Освітня програма'),
        ),
    ]
