# Generated by Django 4.0.1 on 2022-06-29 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0006_student_educational_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalprogram',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ed_prog_department', to='methodist.department', verbose_name='Відділення'),
        ),
        migrations.AlterField(
            model_name='group',
            name='educational_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_ed_prog', to='methodist.educationalprogram', verbose_name='Освітня програма'),
        ),
    ]
