# Generated by Django 4.0.1 on 2022-07-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0007_alter_educationalprogram_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='telegram_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
