# Generated by Django 4.0.1 on 2022-07-05 19:06

from django.db import migrations
import methodist.managers.user


class Migration(migrations.Migration):

    dependencies = [
        ('methodist', '0008_student_telegram_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('methodist.customuser',),
            managers=[
                ('objects', methodist.managers.user.UserManager()),
            ],
        ),
    ]
